# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "SumitRamchandra-patch-1" ]
  pull_request:
    branches: [ "SumitRamchandra-patch-1" ]

jobs:
  Backend-Setup:

    runs-on: self-hosted #runner

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      
    - run: cd /home/fs-lp-56/actions-runner/_work/wanderlust/wanderlust/backend  
    - run: ls -a
    - run: cd backend && npm i 
    - run: cp /home/fs-lp-56/actions-runner/_work/wanderlust/wanderlust/backend/.env.sample .env
    - run: cd backend && npm start
